pipeline {
    environment {
        registry = "https://docker.mjamsek.com"
        registryCredential = "nexus-username"
        dockerImageTag = "docker.mjamsek.com/tasker"
        dockerImage = ""
        version = ""
    }

    agent any

    tools {
        maven "mvn-3.6"
        nodejs "node-12"
        jdk "jdk-13"
    }

    stages {
        stage("Cloning git") {
            steps {
                git branch: "master",
                        credentialsId: "github-username",
                        url: "https://github.com/Jamsek-m/tasker.git"
            }
        }
        stage("Set environment variables") {
            steps {
                script {
                    version = readFile('VERSION').trim()
                }
            }
        }
        stage("Set NPM credentials") {
            steps {
                script {
                    withCredentials([string(credentialsId: 'npm-public', variable: 'NPM_TOKEN')]) {
                        sh "echo //https://nexus.mjamsek.com/repository/npm-public/:_authToken=$NPM_TOKEN > frontend/.npmrc"
                        sh "cat frontend/.npmrc"
                    }
                }
            }
        }
        stage("Packaging application") {
            steps {
                sh "npm install --prefix ./frontend"
                sh "mvn clean package"
            }
        }
        stage("Building docker image") {
            steps {
                script {
                    dockerImage = docker.build dockerImageTag
                }
            }
        }
        stage("Publishing docker image") {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        dockerImage.push("$version")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Cleanup phase") {
            steps {
                sh "docker rmi $dockerImageTag:$version"
                sh "docker rmi $dockerImageTag:latest"
                sh "rm .npmrc"
            }
        }
    }
}