pipeline {
    environment {
        registry = "https://docker.mjamsek.com"
        registryCredential = "nexus-username"
        dockerImageTag = "docker.mjamsek.com/tasker"
        dockerImage = ""
        version = ""
        commitAuthor = ""
    }

    agent any

    tools {
        maven "mvn-3.6"
        nodejs "node-12"
        jdk "jdk-13"
    }

    stages {
        stage("Cloning git") {
            steps {
                git branch: "master",
                        credentialsId: "github-username",
                        url: "https://github.com/Jamsek-m/tasker.git"
            }
        }
        stage("Set environment variables") {
            steps {
                script {
                    version = readFile('VERSION').trim()
                    sh "git --no-pager show -s --format='%ae' > COMMIT_INFO"
                    commitAuthor = readFile("COMMIT_INFO").trim()
                }
            }
        }
        stage("Packaging application") {
            steps {
                dir("frontend") {
                    withNPM(npmrcConfig: 'npm-public-file') {
                        sh "npm install"
                    }
                }
                sh "mvn clean package"
            }
        }
        stage("Building docker image") {
            steps {
                script {
                    dockerImage = docker.build dockerImageTag
                }
            }
        }
        stage("Publishing docker image") {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        dockerImage.push("$version")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Cleanup docker images") {
            steps {
                sh "docker rmi $dockerImageTag:$version"
                sh "docker rmi $dockerImageTag:latest"
            }
        }
    }
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
    }
}