kumuluzee:
  name: tasker
  version: 1.0.0
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/mainDB
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:h2:file:./data/data
      username: ''
      password: ''
      pool:
        max-size: 20
tasker:
  session:
    duration: 3600
  admin:
    username: admin
    password: admin
