kumuluzee:
  name: tasker
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/mainDB
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:h2:file:./h2/baza
      username: ''
      password: ''
      max-pool-size: 20
