kumuluzee:
  name: tasker
  version: 1.0.0
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count, Access-Control-Allow-Credentials"
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:h2:file:./data/data
      username: ''
      password: ''
      pool:
        max-size: 20
  security:
    keycloak:
      json: '{
               "realm": "mjamsek-test",
               "bearer-only": true,
               "auth-server-url": "https://keycloak.mjamsek.com/auth",
               "ssl-required": "external",
               "resource": "tasker-service",
               "confidential-port": 0
             }'
tasker:
  admin:
    username: admin
    password: admin
