create table api_services (base_url varchar(255), healthcheck_url varchar(255), major_version integer, id varchar(255) not null, primary key (id));
create table client_apps (application_url varchar(255), id varchar(255) not null, primary key (id));
create table configuration (id varchar(255) not null, config_key varchar(255) not null, config_value varchar(255), primary key (id));
create table service_deployments (id varchar(255) not null, container_id varchar(255), container_name varchar(255), docker_endpoint_id varchar(255), primary key (id));
create table docker_endpoints (id varchar(255) not null, name varchar(255) not null, url varchar(255) not null, primary key (id));
create table logs (id varchar(255) not null, message varchar(255), severity varchar(255), timestamp timestamp, primary key (id));
create table services (service_type varchar(50) not null, id varchar(255) not null, active boolean, description varchar(255), name varchar(255), version varchar(255), deployment_id varchar(255), primary key (id));
create table web_apps (application_url varchar(255), base_url varchar(255), healthcheck_url varchar(255), major_version integer, id varchar(255) not null, primary key (id));
create table domains (id varchar(255) not null, ssl_enabled boolean, domain varchar(255), primary key (id));
create table servers (id varchar(255) not null, name varchar(255) not null, ip_address varchar(255), primary key (id));
create table service_tokens (id varchar(255) not null, user_id varchar(255) not null, token varchar(255) not null, token_id varchar(255) not null, service_id varchar(255) not null, primary key (id));
create index TOKEN_ID_INDEX on service_tokens(token_id);
create index KEY_UNIQUE_INDEX on configuration (config_key);
alter table configuration add constraint UK_fe9jr3m4w3y3gy1pchksbt7v5 unique (config_key);
alter table docker_endpoints add constraint UK_rby7ea40selhpgk0isap43dlu unique (name);
alter table services add constraint NAME_UNIQ_INDEX unique (name, version);
alter table api_services add constraint FKnjpg9r8t57c6f8kw2o65uub5e foreign key (id) references services;
alter table client_apps add constraint FK1cl0hy6nfomg8mqcanip6e6gp foreign key (id) references services;
alter table service_deployments add constraint FKl5b6soqbyjpg8ftfhksd5v39x foreign key (docker_endpoint_id) references docker_endpoints;
alter table services add constraint FK15pn8oulot7n6s9ws11p8dl1f foreign key (deployment_id) references service_deployments;
alter table web_apps add constraint FKt8ol7xqq527fl66a6ecf3ecmc foreign key (id) references services;
alter table servers add constraint SERVER_NAME_UNIQ_INDEX unique (name);
alter table service_tokens add constraint FK_SERVICE_TOKEN foreign key (service_id) references services;
alter table service_tokens add constraint TOKEN_ID_UNIQUE_INDEX unique (token_id);